version: '3.8'
services:
  db-clinica:
    image: mysql:8.0
    container_name: mysql_clinica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parola
      MYSQL_DATABASE: monitorizare_veterinara
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: